### ISSUE TITLE
Show chat badges (Turbo, Subscriber, Streamer, Mod, Staff etc.)

### ISSUE THREAD

**Issue by pencil** [pencil/rechat#20]
`turbo` and `subscriber` flags (`true`, `false`) are already recorded as well as the `usertype` field (`mod`, `global_mod`, `admin`, `staff`). All that is left is displaying them in the browser extension.

**Comment by goldbattle** [comment]
https://github.com/justintv/Twitch-API/blob/master/v3_resources/chat.md#get-chatchannelbadges

Should get all the badges needed for a channel.

**Comment by tolgap** [comment]
@pencil I have taken a shot at completing @goldbattle 's implementation of chat badges. I have included the user types as well for `mod`, `global_mod`, `admin` and `staff`. The only question left is, where should I open a pull request? To this reop, or to @goldbattle 's repo? I have mostly used code of @goldbattle but I have also included some style changes. (Like variable naming in camelcase instead of underscores as @pencil does it, and moving badge logic to it's own method etc.)

**Comment by goldbattle** [comment]
Make the PR to the main repo.
My PR mainly was a starting point for others.

**Comment by tolgap** [comment]
@goldbattle I'll do it, and thank you for the starting point :)

**Comment by pencil** [comment]
I just merged #26 and will rollout the update soonTM. Thank you for your commitment @goldbattle and @tolgap!
