### ISSUE TITLE
Rechat no longer compatible with Firefox because of addon signing

### ISSUE THREAD

**Issue by SystemPunch** [pencil/rechat#24]
Firefox now has add-on signing as of version 41, and the latest version is unverified, so Firefox will straight up refuse to install it. The signed version on the official add-on repo is version 0.9.1.1, and doesn't work

**Comment by pencil** [comment]
Not much I can do about that. Unfortunately review times are [currently around 10 to 12 weeks](https://blog.mozilla.org/addons/2015/08/12/add-ons-update-69/). I suggest switching to a browser with a functioning add-on reviews system.

**Comment by pencil** [comment]
Update: Looks like it is possible to have your updates automatically signed if you "unlist" your add-on. I did that but ReChat currently [does not support e10s](https://www.reddit.com/r/rechat/comments/3fr0o8/rechat_crashes_the_process_on_every_vod_on/) which is why it will still not work with Firefox 41.
